#!/bin/sh

set -eu

# 環境変数の設定
export LC_ALL=C
export LANG=C
export POSIXLY_CORRECT=1

# urldecode 関数の定義
# shellcheck disable=SC3060
urldecode() {
    url_encoded="${1//+/ }"
    printf '%b' "${url_encoded//%/\\x}"
}

# 設定ファイルのパス
config_file="/workspace/book_manager/book_manager.conf"

# スクリプトディレクトリをPATHに追加
export PATH="/workspace/book_manager/bin:${PATH}"

# 関数の設定
# 設定を保存する関数
save_config() {
    # POSTデータからパラメータを抽出
    csv_file=""
    script_dir=""

    if [ "${REQUEST_METHOD:-GET}" = "POST" ] && [ -n "${CONTENT_LENGTH:-}" ]; then
        # POSTデータを読み込み
        post_data="$(cat)"

        # パラメータを抽出
        raw_csv_file=$(echo "$post_data" | grep -o 'csv_file=[^&]*' | cut -d'=' -f2)
        csv_file=$(urldecode "$raw_csv_file")
        raw_script_dir=$(echo "$post_data" | grep -o 'script_dir=[^&]*' | cut -d'=' -f2)
        script_dir=$(urldecode "$raw_script_dir")
    fi

    # 設定ファイルを作成/更新
    cat > "$config_file" << EOF
# Book Manager Configuration
# Generated by config.cgi

# CSV file path
csv_file="${csv_file}"

# Script directory
script_dir="${script_dir}"

# Environment variables
LC_ALL=C
LANG=C
POSIXLY_CORRECT=1
EOF

    # 成功メッセージを表示
    echo '<div class="result success">設定が保存されました。</div>'
}

# 設定を読み込む関数
load_config() {
    if [ -f "$config_file" ]; then
        # 設定ファイルから変数を読み込み
        . "$config_file"

        # 変数をエスケープして表示
        escaped_csv_file=$(printf '%s' "$csv_file" | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/"/\&quot;/g')
        escaped_script_dir=$(printf '%s' "$script_dir" | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/"/\&quot;/g')
# shellcheck disable=SC1090,SC2153
        . "$CONFIG_FILE"

        # 変数をエスケープして表示
        escaped_csv_file=$(printf '%s' "$CSV_FILE" | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/"/\&quot;/g')
        escaped_script_dir=$(printf '%s' "$SCRIPT_DIR" | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/"/\&quot;/g')

        echo '<div class="result success">現在の設定:</div>'
        echo '<pre>'
        echo "csv_file=$escaped_csv_file"
        echo "script_dir=$escaped_script_dir"
        echo '</pre>'
    else
        echo '<div class="result error">設定ファイルが見つかりません。</div>'
    fi
}

# HTML
echo "Content-Type: text/html; charset=UTF-8"
echo ""

cat << EOF
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>設定結果 - Book Manager</title>
    <link rel="stylesheet" href="../css/style.css">
    <style>
        .result {
            margin: 20px;
            padding: 10px;
            border-radius: 4px;
        }
        .success {
            background-color: #dff0d8;
            color: #3c763d;
        }
        .error {
            background-color: #f2dede;
            color: #a94442;
        }
        pre {
            background-color: #f5f5f5;
            padding: 10px;
            border-radius: 4px;
            overflow-x: auto;
        }
    </style>
</head>
<body>
    <h1>設定結果</h1>
    <p><a href="../html/config.html">設定ページ</a> | <a href="../html/index.html">メニュー</a></p>

EOF

# POSTリクエストの場合は設定を保存
if [ "${REQUEST_METHOD:-GET}" = "POST" ]; then
    save_config
else
    load_config
fi

cat << EOF

</body>
</html>
EOF

