#!/bin/sh

# shellcheck disable=SC1090

set -eu

# 環境変数の設定
export LC_ALL=C
export LANG=C
export POSIXLY_CORRECT=1

# 設定ファイルのパス
config_file="../book_manager.conf"

# 独自コマンドにパスを通す
export PATH="../bin:${PATH}"

# 関数の設定
# 設定を保存する関数
save_config() {

    # POSTデータからパラメータを抽出
    csv_file=""
    code_server=""

    if [ "${REQUEST_METHOD:-GET}" = "POST" ] && [ -n "${CONTENT_LENGTH:-}" ]; then
        # POSTデータを読み込み
        post_data="$(cat)"

        # POSTデータをurldecode
		decoded_post=$(echo "$post_data" | urldecode)

        # パラメータを抽出
        csv_file=$(echo "${decoded_post}" | grep -o 'csv_file=[^&]*' | cut -d'=' -f2)
        code_server=$(echo "${decoded_post}" | grep -o 'code_server=[^&]*' | cut -d'=' -f2)
    fi

    # 値から先頭と末尾のダブルクォートを削除
    csv_file=$(echo "${csv_file}" | sed 's/^"//;s/"$//')
    code_server=$(echo "${code_server}" | sed 's/^"//;s/"$//')

    # 設定ファイルを作成/更新
    cat > "${config_file}" <<- EOF
		# Book Manager Configuration
		# Generated by config.cgi

		# CSV file path
		csv_file="${csv_file}"

		# code-server URL
		code_server="${code_server}"

		# Environment variables
		LC_ALL=C
		LANG=C
		POSIXLY_CORRECT=1
	EOF

    # 成功メッセージを表示
    echo '<div class="result success">設定が保存されました。</div>'

}

# 設定を読み込む関数
load_config() {

	# 設定ファイルの有無を確認
    if [ -f "${config_file}" ]; then
        # 設定ファイルからcsv_fileの値を抽出
        escaped_csv_file=$(grep '^csv_file=' "${config_file}" | cut -d'=' -f2- | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/"/\&quot;/g')
        # 設定ファイルからcode_serverの値を抽出
        escaped_code_server=$(grep '^code_server=' "${config_file}" | cut -d'=' -f2- | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/"/\&quot;/g')

        cat <<- EOF
			<div class="result success">現在の設定:</div>
			<pre>
			csv_file=${escaped_csv_file}
			code_server=${escaped_code_server}
			</pre>
		EOF

    else

        echo '<div class="result error">設定ファイルが見つかりません。</div>'

    fi

}

# 結果を出力
result() {

	if [ "${REQUEST_METHOD:-GET}" = "POST" ]; then
		save_config
	else
		load_config
	fi

}

# HTML
echo "Content-Type: text/html; charset=UTF-8"
echo ""

cat << EOF
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>設定結果 - Book Manager</title>
    <link rel="stylesheet" href="../css/style.css">
</head>
<body>
    <h1>設定結果</h1>
    <p><a href="../html/settings.html">設定ページ</a> | <a href="../html/index.html">メニュー</a></p>
	$(result)

</body>
</html>
EOF

